package com.cwgplc.studentregistration.dto;

import com.cwgplc.studentregistration.entity.FacultyEntity;

import javax.validation.constraints.*;

public class FacultyRequest {

    @Min(value = 1, groups = UpdateEntityRequest.class, message = "ID must have a value of at least 1")
    @Min(value = 0, groups = CreateEntityRequest.class, message = "ID is autogenerated. Cannot be specified during creation")
    @Max(value = 0, groups = CreateEntityRequest.class,message = "ID is autogenerated. Cannot be specified during creation")
    private int id;


    @Size(groups = {CreateEntityRequest.class,UpdateEntityRequest.class}, message = "Name must be between 5 and 15 Characters", min = 5, max = 15)
    @NotNull(groups = {CreateEntityRequest.class,UpdateEntityRequest.class}, message = "Name cannot be null")
    @NotEmpty(groups = {CreateEntityRequest.class,UpdateEntityRequest.class},message = "Name Cannot Be Empty")
    private String name;

    public String getName() {
        return name;
    }
    public int getId() {
        return id;
    }


    public FacultyEntity toFacultyEntity(){
        return new FacultyEntity( getName(),getId());
    }





}
