package com.cwgplc.studentregistration.dto;

import javax.validation.constraints.*;
import java.time.LocalDate;

public class StudentRequest {


    @Min(value = 1, groups = UpdateEntityRequest.class, message = "ID must have a value of at least 1")
    @Min(value = 0, groups = CreateEntityRequest.class, message = "ID is autogenerated. Cannot be specified during creation")
    @Max(value = 0, groups = CreateEntityRequest.class,message = "ID is autogenerated. Cannot be specified during creation")
    private int id;


    @Size(groups = {CreateEntityRequest.class,UpdateEntityRequest.class}, message = "Name must be between 5 and 15 Characters", min = 5, max = 15)
    @NotNull(groups = {CreateEntityRequest.class,UpdateEntityRequest.class}, message = "Name cannot be null")
    @NotEmpty(groups = {CreateEntityRequest.class,UpdateEntityRequest.class},message = "Name Cannot Be Empty")
    private String name;

    @Size(groups = {CreateEntityRequest.class,UpdateEntityRequest.class}, message = "Name must be between 5 and 15 Characters", min = 5, max = 15)
    @NotNull(groups = {CreateEntityRequest.class,UpdateEntityRequest.class}, message = "Name cannot be null")
    @NotEmpty(groups = {CreateEntityRequest.class,UpdateEntityRequest.class},message = "Name Cannot Be Empty")
    private String lastName;

    @Size(groups = {CreateEntityRequest.class,UpdateEntityRequest.class}, message = "Name must be between 5 and 15 Characters", min = 1, max = 1)
    @NotNull(groups = {CreateEntityRequest.class,UpdateEntityRequest.class}, message = "Name cannot be null")
    @NotEmpty(groups = {CreateEntityRequest.class,UpdateEntityRequest.class},message = "Name Cannot Be Empty")
    private String gender;

    @NotNull(groups = {CreateEntityRequest.class,UpdateEntityRequest.class}, message = "Name cannot be null")
    @NotEmpty(groups = {CreateEntityRequest.class,UpdateEntityRequest.class},message = "Name Cannot Be Empty")
    @Past(message = "Please specify a valid birthdate")
    private LocalDate dob;

    @Min(value = 1, groups = { UpdateEntityRequest.class, CreateEntityRequest.class}, message = " Department_ID must have a value of at least 1")
    private int departmentID;

    public String getName() {
        return name;
    }

    public int getId() {
        return id;
    }

    public int getDepartmentID(){
        return departmentID;
    }
}
